linters:
  enable:
    - errcheck
    - gosimple
    - unused
    - govet
    - ineffassign
    - staticcheck
    - predeclared
    - asciicheck
    - gosmopolitan
    - loggercheck
    - testifylint
    - usestdlibvars
    - noctx
    - goconst
    - wrapcheck
    - errorlint
    - unconvert
    - unparam
    - gocritic
    - prealloc
    - copyloopvar
    - promlinter
    - protogetter
    - rowserrcheck
    - sqlclosecheck
    - revive
    - gosec
    - dupl

linters-settings:
  gocyclo:
    min-complexity: 20

run:
  timeout: 10m
  tests: false
